ALTER TABLE "Goal" ADD COLUMN "interestsTarget" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Goal" ADD COLUMN "meetingsTarget" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Goal" ADD COLUMN "salesTarget" INTEGER NOT NULL DEFAULT 0;

CREATE TABLE "MemberProfile" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "avatarUrl" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
